language: cpp

compiler:
  - gcc
      
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    packages:
      - build-essential
      - gcc-5
      - g++-5
      - git
      - cmake
      - protobuf-compiler
      - libprotobuf-dev

script:
  - make proto
  - make