sudo: true

dist: trusty

language: cpp

compiler:
  - gcc
      
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    packages:
      - build-essential
      - git
      - cmake
      - gcc-4.8
      - g++-4.8
      - protobuf-compiler
      - libprotobuf-dev

script:
  - make proto
  - make